COLUMN DATA_TYPE FORMAT A30
SELECT DATA_TYPE,
DECODE (INSTR(COLUMN_NAME,'_',-1),0,'NONE',   
        SUBSTR(COLUMN_NAME, (INSTR(COLUMN_NAME,'_',-1)))) SUFFIX, COUNT(*)
FROM USER_TAB_COLUMNS
GROUP BY DATA_TYPE,
DECODE (INSTR(COLUMN_NAME,'_',-1),0,'NONE',   
        SUBSTR(COLUMN_NAME, (INSTR(COLUMN_NAME,'_',-1))))
ORDER BY 1,3 DESC;