CREATE TABLE CLASSIFIED_SECTION
(SECTION_NO NUMBER NOT NULL,
 SECTION_TITLE VARCHAR2(50),
 BASE_RATE_PER_WORD NUMBER(4,3),
CONTACT_EDITOR CLASSMATE.CONTACT_TABLE)
 NESTED TABLE CONTACT_EDITOR
 STORE AS NESTED_EDITORS;
