CREATE GLOBAL TEMPORARY TABLE EDITOR_REVENUE
ON COMMIT PRESERVE ROWS
AS 
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EDITOR,
   SUM(CA.PRICE) ANNUAL_REVENUE
   FROM CLASSIFIED_AD CA JOIN EMPLOYEE E 
   ON (CA.INTAKE_EDITOR_ID = E.EMPLOYEE_ID)
WHERE TO_CHAR(CA.PLACED_DATE, 'YYYY') = '2003'
   GROUP BY FIRST_NAME || ' ' || LAST_NAME;
