REM ***************************
REM       Run script when logged in as:
REM            CLASSMATE/classpath
REM **************************

CREATE TYPE EDITOR_INFO AS OBJECT
 (PRIMARY_EDITOR CHAR(1),
  EDITOR_ID NUMBER(10))
/
CREATE TYPE CONTACT_TABLE AS 
    TABLE OF EDITOR_INFO
/
CREATE TYPE PHONE_ARRAY AS 
VARRAY (10) OF VARCHAR2(20)
/
CREATE TYPE CUSTOMER_ADDRESS_TYPE AS OBJECT
 ( CUSTOMER_ID VARCHAR2(10)
   , POBOX_SUITE VARCHAR2(24)
   , STREET_ADDRESS VARCHAR2(40)
   , CITY VARCHAR2(30)
   , STATE VARCHAR2(2)
   , COUNTRY VARCHAR2(20)
  )
/
CREATE TYPE PRICE_IN_CURRENCY AS 
VARRAY (5) OF NUMBER(12, 5)
/
CREATE TYPE PRICE_HISTORY AS
 VARRAY (10) OF NUMBER(8,5)
/
CREATE TYPE CHOSENSONG AS OBJECT 
( SONG_ID NUMBER, SEQUENCE_NO NUMBER(2, 0))
/
CREATE TYPE SONGLIST AS 
VARRAY (15) OF CHOSENSONG
/
CREATE TYPE CHANGEAUDIT AS OBJECT 
( EMPLOYEE_ID NUMBER, CHANGE_DATETIME DATE)
/
CREATE TYPE CHANGES AS 
VARRAY (5) OF CHANGEAUDIT
/