LOAD DATA
   INFILE 'data\Chapter11\ch11.dat' 
INTO TABLE client APPEND
FIELDS TERMINATED BY "," TRAILING NULLCOLS
(
    CLIENT_ID INTEGER,
    FIRST_NAME CHAR(10),
    LAST_NAME CHAR(20),
    CONTACT_PHONE CHAR(15),
    CONTACT_EMAIL CHAR(30)
)