SELECT C.CLIENT_ID,
C.FIRST_NAME,
C.LAST_NAME,
COUNT(W.AD_ID) NUMBER_OF_ADS
FROM CLASSMATE.CLIENT C JOIN CLASSMATE.WANT_AD W
ON C.CLIENT_ID = W.AD_OWNER
GROUP BY C.CLIENT_ID,
C.FIRST_NAME,
C.LAST_NAME