ALTER TABLE CH08SURGERY 
RENAME COLUMN PATIENT_FISRT_NAME TO PATIENT_FIRST_NAME;

ALTER TABLE CH08SURGERY 
ADD (OUTCOME VARCHAR2(40), OPERATING_ROOM_NO CHAR(4));

ALTER TABLE CH08SURGERY 
MODIFY (DOCTOR_NAME VARCHAR2(20));
REM ORA-01441: cannot decrease column length because some value is too big

ALTER TABLE CH08SURGERY 
MODIFY (DOCTOR_NAME VARCHAR2(25));

ALTER TABLE CH08SURGERY 
SET UNUSED (PROCEDURES, OUTCOME);

ALTER TABLE CH08SURGERY 
ADD (PROCEDURES CLASSMATE.PROCEDURES_ARRAY, OUTCOME NUMBER(2,0));

ALTER TABLE CH08SURGERY 
DROP UNUSED COLUMNS;
