DROP TABLE CH08HOUSE_REPAIR;
DROP TABLE CH08REPAIR_TYPE;
CREATE TABLE CH08REPAIR_TYPE 
(REPAIR_TYPE VARCHAR2(10) NOT NULL, 
DESCRIPTION VARCHAR2(500) NOT NULL,   
 ESTIMATED_HOURS NUMBER(10,2) NOT NULL,   
 CONSTRAINT CH08REPAIR_TYPE_PK PRIMARY KEY(REPAIR_TYPE))
/
CREATE TABLE CH08HOUSE_REPAIR 
(HOUSE_NAME VARCHAR2(20) NOT NULL, 
REPAIR_NAME VARCHAR2(40) NOT NULL,
REPAIR_TYPE VARCHAR2(10) NOT NULL, 
HOURS NUMBER(8,2) NOT NULL, 
MATERIALS_COST NUMBER(10, 2) NOT NULL,
DATE_STARTED DATE NOT NULL, 
DATE_COMPLETED DATE NOT NULL,
CONSTRAINT CH08HOUSE_PK 
   PRIMARY KEY(HOUSE_NAME,REPAIR_NAME),
CONSTRAINT CH08REPAIR_FK 
   FOREIGN KEY(REPAIR_TYPE) 
   REFERENCES CH08REPAIR_TYPE(REPAIR_TYPE))  
/
INSERT INTO CH08REPAIR_TYPE VALUES ('PERFECT','This repair is done with all matching tools and using the finest, most expensive materials imaginable.', 1000);
INSERT INTO CH08REPAIR_TYPE VALUES ('SLOPPY','This repair is done with amateur craftsmen who just want to experiment with stuff they saw on TV.', 150);
INSERT INTO CH08REPAIR_TYPE VALUES ('DANGEROUS','This repair is usually done at night when no one is looking and with sub-standard materials.', 8);
INSERT INTO CH08HOUSE_REPAIR VALUES ('Corner Grocery Store','New awning over window','SLOPPY',187, 2050.00, '01-JUN-2004','02-JUL-2004');
INSERT INTO CH08HOUSE_REPAIR VALUES ('Ma and Pa','Roof hole repaired','PERFECT',875.34, 10354.00, '15-MAY-2004','31-OCT-2004');
INSERT INTO CH08HOUSE_REPAIR VALUES ('Bus Stop','Repair broken glass','DANGEROUS',10, 500.00, '09-JUN-2004','10-JUN-2004');
COMMIT;