CREATE TABLE MOVIEMAKER 
(MOVIE_ID NUMBER(10),
 MOVIE_TITLE VARCHAR2(30),
 PRODUCER VARCHAR2(30),
 REVIEW CLOB,
 MOVIE BLOB)
LOB (REVIEW, MOVIE) STORE AS 
    (TABLESPACE <tablespace>  
     DISABLE STORAGE IN ROW
     CHUNK <chunk>
     STORAGE (INITIAL <nn> NEXT <nn> MAXEXTENTS UNLIMITED));
     