CREATE TABLE ZIPREFERENCES
(ZIPCODE VARCHAR2(10) NOT NULL, 
 CITY VARCHAR2(40) NOT NULL, 
 STATE VARCHAR2(10) NOT NULL, 
 PROVINCE VARCHAR2(10) NOT NULL, 
 COUNTRY VARCHAR2(20) NOT NULL, 
 CONSTRAINT ZIP_PK PRIMARY KEY(ZIPCODE))