SET ECHO ON
-- SUCCESSFUL INSERT (3 ROWS)
ALTER TABLE EMPLOYEE ADD (PHONE_NUMBER VARCHAR2(32));
INSERT INTO EMPLOYEE VALUES
(299, 'DELIVERY PERSON','Blue','McDieter','840-277-1234');
INSERT INTO EMPLOYEE VALUES
(300, 'DELIVERY PERSON','Amanda','Tolman','840-233-1998');
INSERT INTO EMPLOYEE VALUES
(301, 'DELIVERY PERSON','Mark','Perry','840-239-8467');
-- SUCCESSFUL UPDATE (2 ROWS)
UPDATE EMPLOYEE SET
FIRST_NAME = 'Skyler' WHERE EMPLOYEE_ID = 299;
UPDATE EMPLOYEE SET
PHONE_NUMBER='840-293-3388', JOB_TITLE='Collections'
WHERE EMPLOYEE_ID = 300;
-- SUCCESSFUL SELECT 
SELECT PHONE_NUMBER FROM EMPLOYEE
WHERE EMPLOYEE_ID = 300;
