/* Creates tables used in Chapter 9 examples */
DROP TABLE CLASSMATE.CH09LIBRARYBOOK
/
DROP TABLE CLASSMATE.CH09LIBRARYBOOK
/
CREATE TABLE CLASSMATE.CH09LIBRARYBOOK 
(TITLE VARCHAR2(50) NOT NULL,
 AUTHOR VARCHAR2(50), 
 ISBN_NO VARCHAR2(15), 
 PUB_DATE DATE,
 DEWEY_DECIMAL VARCHAR2(10), 
 DESCR VARCHAR2(4000))
/
INSERT INTO CLASSMATE.CH09LIBRARYBOOK VALUES
('Oracle9i for Dummies','Carol McCullough-Dieter','0-7645-0880-6','01-FEB-2002','756-McC','Guide to Oracle9i')
/
INSERT INTO CLASSMATE.CH09LIBRARYBOOK VALUES
('Beatles Songbook','Joe Cartwright','0-9876-0809-0','01-MAY-1989','152-W','Includes guitar chord markings')
/
DROP TABLE CLASSMATE.CH09MORTGAGE_HISTORY
/
CREATE TABLE CLASSMATE.CH09MORTGAGE_HISTORY
     (LOAN_NO NUMBER,
      ACCT_NO NUMBER,
      DATE_CREATED DATE,
      MORTGAGE_AMOUNT NUMBER)
   PARTITION BY HASH (DATE_CREATED)
   PARTITIONS 2 
   STORE IN (USERS, USER_AUTO)
/
DROP TABLE CLASSMATE.CH09MORTGAGE_CLIENT
/
CREATE TABLE CLASSMATE.CH09MORTGAGE_CLIENT
     (ACCT_NO NUMBER,
      LOAN_DATE DATE,
      MORTGAGE_AMOUNT NUMBER, 
      MORTGAGE_RATE NUMBER(10,4),
      NUMBER_OF_YEARS NUMBER (4,0))
   PARTITION BY RANGE (LOAN_DATE)
   (PARTITION OLDER VALUES LESS THAN (TO_DATE('01-JAN-1988','DD-MON-YYYY'))
   TABLESPACE USERS,
    PARTITION NEWER VALUES LESS THAN (TO_DATE('01-JAN-1995','DD-MON-YYYY'))
    TABLESPACE USER_AUTO) 
/
INSERT INTO CLASSMATE.CH09MORTGAGE_CLIENT VALUES
(100, '01-JAN-1985', 500000, .1005, 30)
/
INSERT INTO CLASSMATE.CH09MORTGAGE_CLIENT VALUES
(105, '01-JAN-1990', 150000, .064, 30)
/
COMMIT
/
 