INSERT INTO CLASSMATE.CLASSIFIED_AD VALUES
(1, 349, 'The BEST BUY! Great deal for new car owners. Car shine cloth. 2 for $1. Call Al at 333-4444.',
300, 400, 7.50, '07-MAR-2004', '08-MAR-2004','15-MAR-2004',INTERVAL '7' DAY,'H')
/
INSERT INTO CLASSMATE.CLASSIFIED_AD VALUES
(2, 350, 'Guitar. New, must see. Jimmy H at 334-3444.',
200, 400, 2.50, '09-MAR-2004', '10-MAR-2004','15-MAR-2004',INTERVAL '2' DAY,'L')
/
INSERT INTO CLASSMATE.CLASSIFIED_AD VALUES
(3, 355, 'BEST BUY - Tires. Retreads. Buy now for winter. Joe Tires at 223-4444.',
100, 400, 7.50, '15-MAR-2004', '15-MAR-2004','17-MAR-2004',INTERVAL '3' DAY,'L')
/
COMMIT
/

INSERT INTO CLASSMATE.EMPLOYEE VALUES
(400, 'EDITOR', 'Jake', 'Wellsley')
/
INSERT INTO CLASSMATE.CUSTOMER (CUSTOMER_ID, CONTACT_NAME, DISCOUNT_PERCENT,
BUSINESS_NAME, BUSINESS_TYPE) VALUES
(100, 'Joe Baker',4.5, 'Joe Tires','Sole Proprietor' )
/
INSERT INTO CLASSMATE.CUSTOMER (CUSTOMER_ID, CONTACT_NAME, DISCOUNT_PERCENT,
BUSINESS_NAME, BUSINESS_TYPE) VALUES
(200, 'James Hendrix',null, 'Purple Days Music Store','Partnership' )
/
INSERT INTO CLASSMATE.CUSTOMER (CUSTOMER_ID, CONTACT_NAME, DISCOUNT_PERCENT,
BUSINESS_NAME, BUSINESS_TYPE) VALUES
(300, 'Sandra Dee',5.7, 'St. John''s Dollar Shoppe','Non-profit' )
/
INSERT INTO CLASSMATE.CLASSIFIED_SECTION (SECTION_NO, SECTION_TITLE, 
BASE_RATE_PER_WORD, PRIORITY_RATE_PER_WORD) VALUES
  (349, 'Automobile Supplies', .75, .85)
/
INSERT INTO CLASSMATE.CLASSIFIED_SECTION (SECTION_NO, SECTION_TITLE, 
BASE_RATE_PER_WORD, PRIORITY_RATE_PER_WORD) VALUES
(350, 'Musical Instruments', .50, .65)
/
INSERT INTO CLASSMATE.CLASSIFIED_SECTION (SECTION_NO, SECTION_TITLE, 
BASE_RATE_PER_WORD, PRIORITY_RATE_PER_WORD) VALUES
(355, 'Automobile Parts', .75, .85)
/
COMMIT
/