SET ECHO ON 
SET FEEDBACK ON 
REM *************** DROP ALL TABLES BEFORE STARTING **********
DROP TABLE CLASSMATE.CH09DOGSHOW CASCADE CONSTRAINTS;
DROP TABLE CLASSMATE.CH09DOG;
DROP TABLE CLASSMATE.CH09DOGOWNER CASCADE CONSTRAINTS;
DROP TABLE CLASSMATE.CH09WORLD;
DROP TABLE CLASSMATE.EXCEPTIONS;
REM ***************** Perform all the step-by-step tasks in Chapter 10 *****
REM *************** Not null constraint ************
CREATE TABLE CLASSMATE.CH09DOGSHOW
(DOGSHOWID NUMBER NOT NULL,
 SHOW_NAME VARCHAR2(40) NOT NULL,
 DATE_ADDED DATE DEFAULT SYSDATE NOT NULL);
INSERT INTO CLASSMATE.CH09DOGSHOW
(DOGSHOWID, SHOW_NAME) VALUES
(1, 'AKC Portland');
ALTER TABLE CLASSMATE.CH09DOGSHOW
MODIFY (SHOW_NAME NULL);
ALTER TABLE CLASSMATE.CH09DOGSHOW
MODIFY (SHOW_NAME NOT NULL);
REM ************* Primary Key constraint ****************
CREATE TABLE CLASSMATE.CH09DOGOWNER
(OWNER_ID NUMBER CONSTRAINT CH09_PK PRIMARY KEY,
 OWNER_NAME VARCHAR2(50),
 MEMBER_OF_AKC CHAR(3) DEFAULT 'NO',
 YEARS_EXPERIENCE NUMBER(2,0));
ALTER TABLE CLASSMATE.CH09DOGOWNER
RENAME CONSTRAINT CH09_PK TO CH09_DOG_OWNER_PK;
ALTER TABLE CLASSMATE.CH09DOGOWNER
DROP CONSTRAINT CH09_DOG_OWNER_PK;
ALTER TABLE CLASSMATE.CH09DOGOWNER
ADD CONSTRAINT CH09_DOG_OWNER_PK PRIMARY KEY (OWNER_ID) DISABLE;
ALTER TABLE CLASSMATE.CH09DOGOWNER
MODIFY CONSTRAINT CH09_DOG_OWNER_PK ENABLE;
REM **************** Unique key constraint ****************
CREATE TABLE CLASSMATE.CH09WORLD
(COUNTRY VARCHAR2(10),
 PERSON_ID NUMBER,
 US_TAX_ID NUMBER(10) CONSTRAINT US_TAX_UNIQUE UNIQUE,
 FIRST_NAME VARCHAR2(10),
 LAST_NAME VARCHAR2(20),
 CONSTRAINT CH09WORLD_PK PRIMARY KEY (COUNTRY, PERSON_ID));
ALTER TABLE CLASSMATE.CH09WORLD 
MODIFY CONSTRAINT US_TAX_UNIQUE DISABLE;
INSERT INTO CLASSMATE.CH09WORLD VALUES ('USA',10005, 98877665, 'Sean','Watson');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('ENGLAND',33998, null, 'Blake','Smythe');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('INDIA',1087005, null, 'Martha','Lakshmi');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('JAPAN',90154, null, 'Ellenore','Kiyoto');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('USA',1235, null, 'David','Earl');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('USA',39986, 20192761, 'Beth','Blanks');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('USA',100005, 98877665, 'Sean','Watson');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('CHINA',22995, null, 'Kim','Wu');
INSERT INTO CLASSMATE.CH09WORLD VALUES ('USA',39968, 20192761, 'Beth','Blanks');
COMMIT;
create table CLASSMATE.exceptions(row_id rowid,
	                owner varchar2(30),
	                table_name varchar2(30),
		        constraint varchar2(30));
REM ********* The following ALTER TABLE command fails deliberatly (this is okay) *****
ALTER TABLE CLASSMATE.CH09WORLD 
MODIFY CONSTRAINT US_TAX_UNIQUE ENABLE VALIDATE
EXCEPTIONS INTO CLASSMATE.EXCEPTIONS;
SELECT E.CONSTRAINT, W.* 
FROM CLASSMATE.CH09WORLD W JOIN CLASSMATE.EXCEPTIONS E ON (W.ROWID = E.ROW_ID)
ORDER BY W.US_TAX_ID;
REM ******************** Foreign key constraint ****************
CREATE TABLE CLASSMATE.CH09DOG
(DOG_ID NUMBER,
 OWNER_ID NUMBER(10) ,
 DOG_NAME VARCHAR2(20),
 BIRTH_DATE DATE,
 CONSTRAINT CH09DOGOWNER_FK 
     FOREIGN KEY (OWNER_ID) REFERENCES CLASSMATE.CH09DOGOWNER 
     DEFERRABLE INITIALLY IMMEDIATE);
REM ********* The following INSERT command fails deliberatly (this is okay) *****
INSERT INTO CLASSMATE.CH09DOG VALUES
(1,2,'Chow Moon','15-JAN-02');
SET CONSTRAINTS ALL DEFERRED;
INSERT INTO CLASSMATE.CH09DOG VALUES
(1,2,'Chow Moon','15-JAN-02');
INSERT INTO CLASSMATE.CH09DOGOWNER VALUES
(2, 'Jack Maylew','YES', 3.5);
COMMIT;
SET CONSTRAINTS ALL IMMEDIATE;
ALTER TABLE CLASSMATE.CH09DOGOWNER 
DROP CONSTRAINT CH09_DOG_OWNER_PK CASCADE;
ALTER TABLE CLASSMATE.CH09DOGOWNER 
ADD CONSTRAINT CH09_DOG_OWNER_PK PRIMARY KEY(OWNER_ID);
ALTER TABLE CLASSMATE.CH09DOG 
ADD CONSTRAINT CH09DOGOWNER_FK FOREIGN KEY (OWNER_ID)
REFERENCES CH09DOGOWNER 
ON DELETE CASCADE;
DELETE FROM CLASSMATE.CH09DOGOWNER WHERE OWNER_ID = 2;
SELECT * FROM CLASSMATE.CH09DOG;
REM ***************** Check constraints ****************
ALTER TABLE CLASSMATE.CH09DOGOWNER
ADD CONSTRAINT AKC_YN CHECK (MEMBER_OF_AKC IN ('YES','NO'));
ALTER TABLE CLASSMATE.CH09DOGSHOW ADD CONSTRAINT ALL_CAPS 
CHECK (SHOW_NAME = UPPER(SHOW_NAME)) DISABLE;
UPDATE CLASSMATE.CH09DOGSHOW SET SHOW_NAME = UPPER(SHOW_NAME);
ALTER TABLE CLASSMATE.CH09DOGSHOW MODIFY CONSTRAINT ALL_CAPS ENABLE;
ALTER TABLE CLASSMATE.CH09WORLD ADD CONSTRAINT CHK_NAMES
CHECK ((FIRST_NAME IS NOT NULL OR LAST_NAME IS NOT NULL)
        AND(FIRST_NAME <> LAST_NAME));
REM ********* The following INSERT command fails deliberatly (this is okay) *****
INSERT INTO CLASSMATE.CH09WORLD VALUES
 ('USA',1995, 99877689, 'Jeremy','Jeremy');
REM ********* The following INSERT command fails deliberatly (this is okay) *****
INSERT INTO CLASSMATE.CH09WORLD VALUES 
('USA',1995, 99877689, NULL, NULL);
INSERT INTO CLASSMATE.CH09WORLD VALUES 
('USA',1995, 99877689, 'Jeremy', NULL);
COMMIT;

REM ************* Data Dictionary Views *************
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, 
STATUS, SEARCH_CONDITION
FROM ALL_CONSTRAINTS
WHERE OWNER='CLASSMATE' ORDER BY TABLE_NAME;

 
