/* log in as SYSTEM and run this script */
SET ECHO Off
set termout off
drop user CLASSMATE cascade;
set termout on
CREATE USER CLASSMATE  PROFILE DEFAULT 
    IDENTIFIED BY CLASSPASS DEFAULT TABLESPACE USERS 
    ACCOUNT UNLOCK;
GRANT CONNECT TO CLASSMATE;
GRANT RESOURCE TO CLASSMATE;
CREATE TABLE CLASSMATE.CLIENTS 
   (CLIENT_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(10) NOT NULL,
    LAST_NAME VARCHAR2(20)  NOT NULL,
    CONTACT_PHONE VARCHAR2(15),
    CONTACT_EMAIL VARCHAR2(30), 
    CONSTRAINT CLIENT_PK PRIMARY KEY(CLIENT_ID))  
    TABLESPACE USERS ;
CREATE TABLE CLASSMATE.WANT_AD 
   (AD_ID NUMBER(10) NOT NULL, 
    HEADLINE VARCHAR2(20) NOT NULL,
    AD_TEXT VARCHAR2(50), 
    AD_OWNER NUMBER(10) NOT NULL, 
    CONSTRAINT T_AD_PK PRIMARY KEY(AD_ID))  
    TABLESPACE USERS ;
CREATE OR REPLACE VIEW CLASSMATE.CLIENT_VIEW AS 
    SELECT C.CLIENT_ID, 
C.FIRST_NAME, 
C.LAST_NAME, 
COUNT(W.AD_ID) NUMBER_OF_ADS 
FROM CLASSMATE.CLIENTS C JOIN CLASSMATE.WANT_AD W
ON C.CLIENT_ID = W.AD_OWNER 
GROUP BY C.CLIENT_ID, 
C.FIRST_NAME, 
C.LAST_NAME;
/*  this table intentionally dropped and recreated to make the CLIENT_VIEW view invalid.*/
DROP TABLE CLASSMATE.CLIENTS;
CREATE TABLE CLASSMATE.CLIENT
   (CLIENT_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(10) NOT NULL,
    LAST_NAME VARCHAR2(20)  NOT NULL,
    CONTACT_PHONE VARCHAR2(15),
    CONTACT_EMAIL VARCHAR2(30), 
    CONSTRAINT CLIENT_PK PRIMARY KEY(CLIENT_ID))  
    TABLESPACE USERS ;
ALTER TABLE CLASSMATE.WANT_AD 
    ADD (CONSTRAINT WANT_AD_OWNER_FK FOREIGN KEY(AD_OWNER) 
    REFERENCES CLASSMATE.CLIENT(CLIENT_ID)) ;
CREATE INDEX CLASSMATE.TITLE_X 
    ON CLASSMATE.WANT_AD(HEADLINE) 
    TABLESPACE USERS;
CREATE VIEW CLASSMATE.WANT_AD_COMPLETE_VIEW AS 
   SELECT W.HEADLINE,
   W.AD_TEXT,
   'Contact: ' ||
   C.FIRST_NAME || ' ' ||
   C.LAST_NAME CONTACT,
   'Phone: ' || C.CONTACT_PHONE PHONE,
   'Email: ' || C.CONTACT_EMAIL EMAIL
   FROM WANT_AD W, CLIENT C
   WHERE W.AD_OWNER = C.CLIENT_ID;
/* ------------ Add Data to Client Table -------------- */
INSERT INTO CLASSMATE.CLIENT VALUES
(1028, 'Mark', 'Wilsonville', '800-222-3333','markw@hhhiii.net');
INSERT INTO CLASSMATE.CLIENT VALUES
(1029, 'Noni', 'Brook', '800-321-3987','nbrooks@earthly.org');
INSERT INTO CLASSMATE.CLIENT VALUES
(1030, 'Jack', 'Rueda Jr.', '800-349-0987','jrjunior@handman.lis');
INSERT INTO CLASSMATE.CLIENT VALUES
(1031, 'Windy', 'Storm', '899-0675','windy@stormsrus');
INSERT INTO CLASSMATE.CLIENT VALUES
(1035, 'Pat', 'Powell', '808-321-1234','pat.powell@brains.inc');
INSERT INTO CLASSMATE.CLIENT VALUES
(102, 'Leslie', 'Moore', '876-0987','leslie@moore.jet');
INSERT INTO CLASSMATE.WANT_AD VALUES
(101, 'Wanted: Ad Writer','Must be able to type 100 wpm', 1028);
COMMIT;